import { Hono } from "hono";
import type { Env } from "../env";
import { createSupabaseClient } from "../services/supabase";
import { wrapProofDocument } from "../lib/factory-v2/document-shell";
import { isFactoryV2Skin } from "../lib/factory-v2/strategy-skin";
import { getOrCreateSkin } from "../lib/factory-v2/strategy-skin-store";
import {
  loadRealBusiness,
  buildRealIdentity,
  MissingContextError,
  BusinessNotFoundError,
} from "../lib/factory-v2/strategy-context";
import { generateAssessmentSpec } from "../lib/factory-v2/assessment-generator";
import { buildAssessmentPage } from "../lib/factory-v2/assessment-recipe";
import type { AssessmentBuildSpec } from "../lib/factory-v2/assessment-spec-schema";
import { isFontPairing, DEFAULT_FONT_PAIRING } from "../lib/factory-v2/textos-style-layer";

// ─────────────────────────────────────────────────────────────────────────────
// TEMP DEV — factory-v2 Assessment app (Phase 3 /dev/ proof, retire at cutover).
//
//   GET /:slug              → themed Assessment wizard page for a REAL business
//                             (real context + no-fallbacks, stored skin). The
//                             scoring SPEC is generated by the LLM ONCE at
//                             build time and cached in KV; runtime scoring is
//                             CLIENT-SIDE (no server call on submit, no result
//                             endpoint).
//   GET /:slug?debug=spec   → the generated/cached spec as JSON.
//   GET /:slug?regen=1      → force-regenerate the spec.
//
// Assets load absolute from the textos-web origin (the Worker has no /homer/*).
// ─────────────────────────────────────────────────────────────────────────────

const HOMER_ASSET_BASE = "https://textos-web-test.pages.dev";

const app = new Hono<{ Bindings: Env }>();

function specKey(businessId: string): string {
  return `fv2:asmt-spec:${businessId}`;
}

async function getOrGenSpec(
  c: { env: Env },
  businessId: string,
  identity: { name: string; summary: string },
  forceRegen: boolean,
): Promise<AssessmentBuildSpec> {
  const kv = c.env.SNAPSHOT_KV;
  const key = specKey(businessId);
  if (kv && !forceRegen) {
    const cached = await kv.get(key);
    if (cached) {
      try {
        return JSON.parse(cached) as AssessmentBuildSpec; // validated before it was stored
      } catch {
        /* fall through to regenerate */
      }
    }
  }
  const { spec } = await generateAssessmentSpec(c.env.ANTHROPIC_API_KEY, identity);
  if (kv) await kv.put(key, JSON.stringify(spec), { expirationTtl: 86_400 });
  return spec;
}

app.get("/:slug", async (c) => {
  const slug = c.req.param("slug");
  const client = createSupabaseClient(c.env);

  try {
    const { business, ctx } = await loadRealBusiness(client, slug);
    const identity = buildRealIdentity(slug, business, ctx); // no-fallbacks: throws if incomplete

    const forceRegen = c.req.query("regen") === "1";
    const spec = await getOrGenSpec(c, business.id, identity, forceRegen);

    if (c.req.query("debug") === "spec") {
      const computedMax = spec.questions.reduce((s, q) => s + Math.max(...q.options.map((o) => o.points)), 0);
      return c.json({
        slug,
        business: business.name,
        hero: spec.hero,
        font_pairing: spec.font_pairing,
        dimensions: spec.dimensions,
        question_count: spec.questions.length,
        questions_by_dimension: spec.dimensions.map((d) => ({
          dimension: d.id,
          questions: spec.questions.filter((q) => q.dimension === d.id).length,
        })),
        max_score: spec.scoring.max_score,
        computed_max: computedMax,
        score_bands: spec.scoring.score_bands.map((b) => ({ min: b.min, max: b.max, label: b.label, color: b.color, cards: b.interpretation_cards.length })),
        recommendations: spec.result.recommendations.length,
      });
    }

    const { skin } = await getOrCreateSkin(client, business.id);
    const override = c.req.query("skin");
    const usedSkin = isFactoryV2Skin(override) ? override : skin;

    // TextOS style layer — LLM-chosen pairing; fall back to the documented
    // default only if a stale cached spec lacks/has an invalid one.
    const pairing = isFontPairing(spec.font_pairing) ? spec.font_pairing : DEFAULT_FONT_PAIRING;

    const { innerHtml, inlineScript } = buildAssessmentPage(spec);
    const doc = wrapProofDocument(innerHtml, {
      skin: usedSkin,
      assetBase: HOMER_ASSET_BASE,
      extraScripts: ["/homer/js/pages/form-wizard.js"], // wizard init; Chart.js + CustomChartJs are in vendors/app.mini.js
      inlineScript,
      fontPairing: pairing,
    });
    return c.html(doc, 200, { "x-fv2-skin": usedSkin });
  } catch (err) {
    if (err instanceof BusinessNotFoundError) return c.json({ error: "business_not_found", slug, message: err.message }, 404);
    if (err instanceof MissingContextError) {
      return c.json({ error: "missing_required_context", slug, missing: err.missing, message: err.message }, 422);
    }
    return c.json({ error: "assessment_failed", slug, message: err instanceof Error ? err.message : String(err) }, 502);
  }
});

export default app;
