import { Hono } from "hono";
import type { Env } from "../env";
import { createSupabaseClient } from "../services/supabase";
import { wrapProofDocument } from "../lib/factory-v2/document-shell";
import { isFactoryV2Skin } from "../lib/factory-v2/strategy-skin";
import { getOrCreateSkin } from "../lib/factory-v2/strategy-skin-store";
import {
  loadRealBusiness,
  buildRealIdentity,
  MissingContextError,
  BusinessNotFoundError,
} from "../lib/factory-v2/strategy-context";
import { generateAssessmentSpec } from "../lib/factory-v2/assessment-generator";
import { buildAssessmentPage } from "../lib/factory-v2/assessment-recipe";
import type { AssessmentBuildSpec } from "../lib/factory-v2/assessment-spec-schema";
import { isFontPairing, DEFAULT_FONT_PAIRING } from "../lib/factory-v2/textos-style-layer";
import { CATALOG } from "../lib/component-catalog/index";
import { resolveComponentTokens } from "../lib/component-catalog/design-token-resolver";
import { STYLE_ROLE_COMPONENT, ASSESSMENT_COMPONENT_IDS } from "../lib/factory-v2/assessment-recipe";
import { resolveVendorScripts, BASE_BUNDLE_FULL, BASE_BUNDLE_MINI } from "../lib/component-catalog/vendor-scripts";

// ─────────────────────────────────────────────────────────────────────────────
// TEMP DEV — factory-v2 Assessment app (Phase 3 /dev/ proof, retire at cutover).
//
//   GET /:slug              → themed Assessment wizard page for a REAL business
//                             (real context + no-fallbacks, stored skin). The
//                             scoring SPEC is generated by the LLM ONCE at
//                             build time and cached in KV; runtime scoring is
//                             CLIENT-SIDE (no server call on submit, no result
//                             endpoint).
//   GET /:slug?debug=spec   → the generated/cached spec as JSON.
//   GET /:slug?regen=1      → force-regenerate the spec.
//
// Assets load absolute from the textos-web origin (the Worker has no /homer/*).
// ─────────────────────────────────────────────────────────────────────────────

const HOMER_ASSET_BASE = "https://app.victora.ai";

const app = new Hono<{ Bindings: Env }>();

function specKey(businessId: string): string {
  return `fv2:asmt-spec:${businessId}`;
}

async function getOrGenSpec(
  c: { env: Env },
  businessId: string,
  identity: { name: string; summary: string },
  forceRegen: boolean,
): Promise<AssessmentBuildSpec> {
  const kv = c.env.SNAPSHOT_KV;
  const key = specKey(businessId);
  if (kv && !forceRegen) {
    const cached = await kv.get(key);
    if (cached) {
      try {
        return JSON.parse(cached) as AssessmentBuildSpec; // validated before it was stored
      } catch {
        /* fall through to regenerate */
      }
    }
  }
  const { spec } = await generateAssessmentSpec(c.env.ANTHROPIC_API_KEY, identity);
  if (kv) await kv.put(key, JSON.stringify(spec), { expirationTtl: 86_400 });
  return spec;
}

app.get("/:slug", async (c) => {
  const slug = c.req.param("slug");
  const client = createSupabaseClient(c.env);

  try {
    const { business, ctx } = await loadRealBusiness(client, slug);
    const identity = buildRealIdentity(slug, business, ctx); // no-fallbacks: throws if incomplete

    const forceRegen = c.req.query("regen") === "1";
    const spec = await getOrGenSpec(c, business.id, identity, forceRegen);

    // Phase C debug — prove validation THROWS on an unsupported token (does NOT
    // touch the real spec): score-badge only supports surface 'tinted'.
    if (c.req.query("debug") === "validate") {
      const badge = CATALOG.by_id["score-badge"];
      try {
        resolveComponentTokens(badge, { surface: "card" }); // 'card' ∉ score-badge.supported (['tinted'])
        return c.json({ threw: false, note: "BUG: should have thrown" });
      } catch (err) {
        return c.json({ threw: true, error_name: (err as Error).name, message: (err as Error).message });
      }
    }

    // Phase C debug — the LLM's token picks + the Homer classes they resolve to.
    if (c.req.query("debug") === "style") {
      const roles: Record<string, unknown> = {};
      for (const [role, compId] of Object.entries(STYLE_ROLE_COMPONENT)) {
        const entry = CATALOG.by_id[compId];
        const chosen = (spec.style?.[role as keyof typeof spec.style] ?? {}) as Record<string, string>;
        const { classes, resolved } = resolveComponentTokens(entry, chosen);
        roles[role] = { component: compId, picked: chosen, resolved, homer_classes: classes || "(all default — no override)" };
      }
      return c.json({ slug, business: business.name, font_pairing: spec.font_pairing, style: roles });
    }

    // Part B debug — the assembler-derived vendor scripts (the FULL base bundle).
    if (c.req.query("debug") === "deps") {
      const scripts = resolveVendorScripts(ASSESSMENT_COMPONENT_IDS, BASE_BUNDLE_FULL);
      return c.json({ base_bundle: BASE_BUNDLE_FULL.id, base_files: BASE_BUNDLE_FULL.files, components: ASSESSMENT_COMPONENT_IDS, derived_addon_scripts: scripts });
    }

    // Part B debug — PROVE the throw: resolve against the lean app.mini.js base
    // bundle (no CustomChartJs). Should throw naming chart-radar + CustomChartJs.
    if (c.req.query("debug") === "deps-mini") {
      try {
        const scripts = resolveVendorScripts(ASSESSMENT_COMPONENT_IDS, BASE_BUNDLE_MINI);
        return c.json({ threw: false, note: "BUG: should have thrown under app.mini.js", scripts });
      } catch (err) {
        return c.json({ threw: true, base_bundle: BASE_BUNDLE_MINI.id, error_name: (err as Error).name, message: (err as Error).message });
      }
    }

    if (c.req.query("debug") === "spec") {
      const computedMax = spec.questions.reduce((s, q) => s + Math.max(...q.options.map((o) => o.points)), 0);
      return c.json({
        slug,
        business: business.name,
        hero: spec.hero,
        font_pairing: spec.font_pairing,
        dimensions: spec.dimensions,
        question_count: spec.questions.length,
        questions_by_dimension: spec.dimensions.map((d) => ({
          dimension: d.id,
          questions: spec.questions.filter((q) => q.dimension === d.id).length,
        })),
        max_score: spec.scoring.max_score,
        computed_max: computedMax,
        score_bands: spec.scoring.score_bands.map((b) => ({ min: b.min, max: b.max, label: b.label, color: b.color, cards: b.interpretation_cards.length })),
        recommendations: spec.result.recommendations.length,
      });
    }

    const { skin } = await getOrCreateSkin(client, business.id);
    const override = c.req.query("skin");
    const usedSkin = isFactoryV2Skin(override) ? override : skin;

    // TextOS style layer — LLM-chosen pairing; fall back to the documented
    // default only if a stale cached spec lacks/has an invalid one.
    const pairing = isFontPairing(spec.font_pairing) ? spec.font_pairing : DEFAULT_FONT_PAIRING;

    const { innerHtml, inlineScript, scripts } = buildAssessmentPage(spec);
    const doc = wrapProofDocument(innerHtml, {
      skin: usedSkin,
      assetBase: HOMER_ASSET_BASE,
      extraScripts: scripts, // Part B: assembler-DERIVED from the composed components (was hand-coded)
      inlineScript,
      fontPairing: pairing,
    });
    return c.html(doc, 200, { "x-fv2-skin": usedSkin });
  } catch (err) {
    if (err instanceof BusinessNotFoundError) return c.json({ error: "business_not_found", slug, message: err.message }, 404);
    if (err instanceof MissingContextError) {
      return c.json({ error: "missing_required_context", slug, missing: err.missing, message: err.message }, 422);
    }
    return c.json({ error: "assessment_failed", slug, message: err instanceof Error ? err.message : String(err) }, 502);
  }
});

// ── POST /:slug/publish — build the self-contained Assessment app + upsert the
// business_assets row the existing /api/generated-apps by-slug endpoint serves.
// Test-only (prod needs owner auth, Phase 4). Mirrors the Strategy publish but
// SIMPLER: Assessment is fully client-side — no result endpoint, no postUrl.
app.post("/:slug/publish", async (c) => {
  if (c.env.ENVIRONMENT !== "test") {
    return c.json({ error: "forbidden", message: "publish is test-only in this build" }, 403);
  }
  const slug = c.req.param("slug");
  let body: { app_slug?: string } = {};
  try {
    body = await c.req.json();
  } catch {
    body = {};
  }
  const appSlug = body.app_slug && /^[a-z0-9-]+$/.test(body.app_slug) ? body.app_slug : "charcuterie-iq";

  const client = createSupabaseClient(c.env);
  try {
    // Real context (no-fallbacks: throws if gaudet is missing required fields).
    const { business, ctx } = await loadRealBusiness(client, slug);
    const identity = buildRealIdentity(slug, business, ctx);

    // Stored skin + LLM spec (cached) + font pairing — the verified /dev/ inputs.
    const { skin } = await getOrCreateSkin(client, business.id);
    const spec = await getOrGenSpec(c, business.id, identity, false);
    const pairing = isFontPairing(spec.font_pairing) ? spec.font_pairing : DEFAULT_FONT_PAIRING;

    // Self-contained HTML — identical to the /dev/ output: full app.js base +
    // the assembler-derived add-on scripts (form-wizard). The scorer + radar run
    // entirely client-side in the iframe; NO result endpoint, NO postUrl.
    const { innerHtml, inlineScript, scripts } = buildAssessmentPage(spec);
    const html = wrapProofDocument(innerHtml, {
      skin,
      assetBase: HOMER_ASSET_BASE,
      extraScripts: scripts,
      inlineScript,
      fontPairing: pairing,
    });

    const asset_data = { html, app_title: spec.hero.title, app_tagline: spec.hero.subtitle, app_type: "assessment" };

    // Supersede the slug: update-in-place if a row exists (unique (business_id,
    // app_slug) index), else insert.
    const existing = await client
      .from("business_assets")
      .select("id")
      .eq("business_id", business.id)
      .eq("asset_type", "app")
      .eq("app_slug", appSlug)
      .maybeSingle();
    if (existing.error) throw existing.error;

    let assetId: string;
    let mode: "updated" | "inserted";
    if (existing.data?.id) {
      const upd = await client
        .from("business_assets")
        .update({ asset_data, is_current: true, updated_at: new Date().toISOString() })
        .eq("id", existing.data.id)
        .select("id")
        .single();
      if (upd.error) throw upd.error;
      assetId = upd.data.id as string;
      mode = "updated";
    } else {
      const ins = await client
        .from("business_assets")
        .insert({ business_id: business.id, asset_type: "app", app_slug: appSlug, is_current: true, asset_data })
        .select("id")
        .single();
      if (ins.error) throw ins.error;
      assetId = ins.data.id as string;
      mode = "inserted";
    }

    return c.json({
      published: true,
      mode,
      asset_id: assetId,
      business_slug: business.slug,
      app_slug: appSlug,
      app_type: "assessment",
      skin,
      font_pairing: pairing,
      derived_scripts: scripts,
      site_url: `${HOMER_ASSET_BASE}/sites/${business.slug}/apps/${appSlug}/`,
    });
  } catch (err) {
    if (err instanceof BusinessNotFoundError) return c.json({ error: "business_not_found", slug, message: err.message }, 404);
    if (err instanceof MissingContextError) {
      return c.json({ error: "missing_required_context", slug, missing: err.missing, message: err.message }, 422);
    }
    return c.json({ error: "publish_failed", slug, message: err instanceof Error ? err.message : String(err) }, 500);
  }
});

export default app;
