-- Sprint 5 Phase 1: Business assets tracking
-- Records artifacts generated by free build tasks (images, URLs, documents, tweets, etc.)
-- so they can be re-referenced, displayed, or re-generated without re-running the task.
--
-- Apply via: https://supabase.com/dashboard/project/gnpohaxkwbvoscqhdezu/sql/new

CREATE TABLE IF NOT EXISTS public.business_assets (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id     UUID NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
  task_run_id     UUID REFERENCES public.task_runs(id) ON DELETE SET NULL,

  -- Asset classification
  asset_type      TEXT NOT NULL CHECK (asset_type IN (
    'document', 'image', 'website', 'email', 'tweet',
    'lean_canvas', 'mission_dashboard', 'daycycle_locations'
  )),
  asset_subtype   TEXT,  -- e.g. 'hero_image', 'mission_doc', 'cold_email_1'

  -- Asset content (one of these will be populated depending on asset_type)
  asset_url       TEXT,   -- deployed URLs (slug.app.textos.ai), R2 object URLs
  asset_text      TEXT,   -- inline text assets (tweet body, email body)
  asset_data      JSONB,  -- structured assets (lean canvas sections, location list)

  -- Audit
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Arbitrary metadata: fal.ai model used, generation cost, prompt, etc.
  metadata        JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_business_assets_biz_type
  ON public.business_assets(business_id, asset_type);

CREATE INDEX IF NOT EXISTS idx_business_assets_task
  ON public.business_assets(task_run_id);

-- RLS: owners see their own business assets
ALTER TABLE public.business_assets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users see own business assets" ON public.business_assets
  FOR SELECT
  USING (
    business_id IN (
      SELECT id FROM public.businesses WHERE user_id = auth.uid()
    )
  );

-- ── Verify ────────────────────────────────────────────────────────────────────
-- SELECT column_name, data_type FROM information_schema.columns
-- WHERE table_name = 'business_assets' ORDER BY ordinal_position;
