-- Migration 036: Business Website V2 columns
-- Adds all content and design fields needed for the redesigned /sites/[slug] page
-- New architecture: single Sonnet call generates ALL content + design decisions
-- Apply in Supabase SQL Editor. Do NOT apply via wrangler or CLI.

ALTER TABLE businesses

  -- ── Design fields ────────────────────────────────────────────────
  ADD COLUMN IF NOT EXISTS hero_css_pattern text,

  -- ── Hero content fields ──────────────────────────────────────────
  ADD COLUMN IF NOT EXISTS hero_eyebrow text,
  ADD COLUMN IF NOT EXISTS hero_headline text,
  ADD COLUMN IF NOT EXISTS hero_headline_accent text,
  ADD COLUMN IF NOT EXISTS hero_subhead text,
  ADD COLUMN IF NOT EXISTS hero_cta_label text,
  ADD COLUMN IF NOT EXISTS hero_cta_type text
    CHECK (hero_cta_type IS NULL OR hero_cta_type IN ('calendly', 'email_capture', 'stripe')),

  -- ── ICP (Ideal Customer Profile) section ────────────────────────
  ADD COLUMN IF NOT EXISTS icp_headline text,
  ADD COLUMN IF NOT EXISTS icp_description text,
  ADD COLUMN IF NOT EXISTS icp_signals jsonb NOT NULL DEFAULT '[]'::jsonb,

  -- ── Structured content sections (JSONB arrays/objects) ──────────
  ADD COLUMN IF NOT EXISTS pain_points jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS metrics jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS palate_cleanser jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS why_us jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS nav_links jsonb NOT NULL DEFAULT '[]'::jsonb,

  -- ── "What We Do" section ─────────────────────────────────────────
  ADD COLUMN IF NOT EXISTS what_we_do_eyebrow text,
  ADD COLUMN IF NOT EXISTS what_we_do_headline text,
  ADD COLUMN IF NOT EXISTS what_we_do_body text,

  -- ── Founder section ──────────────────────────────────────────────
  ADD COLUMN IF NOT EXISTS founder_eyebrow text,
  ADD COLUMN IF NOT EXISTS founder_headline text,
  ADD COLUMN IF NOT EXISTS founder_body text;

-- Add helpful comment for future reference
COMMENT ON COLUMN businesses.hero_css_pattern IS 'CSS background pattern generated by Claude (pure CSS, no images)';
COMMENT ON COLUMN businesses.hero_cta_type IS 'CTA routing type: calendly=scheduling, email_capture=lead form, stripe=checkout';
COMMENT ON COLUMN businesses.pain_points IS 'Array of {icon, headline, body} objects for pain points section';
COMMENT ON COLUMN businesses.metrics IS 'Array of {value, label} objects for metrics bar';
COMMENT ON COLUMN businesses.palate_cleanser IS 'Single {type, content, attribution} object for palate cleanser section';
COMMENT ON COLUMN businesses.why_us IS 'Array of {headline, body} objects for why us section';
COMMENT ON COLUMN businesses.nav_links IS 'Array of {label, anchor} objects for navigation menu';
COMMENT ON COLUMN businesses.icp_signals IS 'Array of string signals that identify the ideal customer';