import { describe, it, expect } from 'vitest';
import { assembleApp } from '../assembler';
import type { AssemblerInput } from '../types';
import { STRATEGY_CONTENT } from '../fixtures/strategy.fixture';
import { ASSESSMENT_CONTENT } from '../fixtures/assessment.fixture';
import { CALCULATOR_CONTENT } from '../fixtures/calculator.fixture';

function baseInput(archetype_id: AssemblerInput['archetype_id'], content: unknown): AssemblerInput {
  return {
    archetype_id,
    content,
    business_context: {
      slug: 'idea-1',
      name: 'Idea Corp',
      operator_url: 'https://example.com/op',
      accent_color_hex: '#c8832a',
    },
    app_id: '11111111-1111-1111-1111-111111111111',
    api_base: 'https://textos-agent-test.example.workers.dev',
    frontend_url: 'https://textos-web-test.example.pages.dev',
  };
}

describe('assembleApp — end-to-end smoke', () => {
  it.each([
    ['strategy', STRATEGY_CONTENT] as const,
    ['assessment', ASSESSMENT_CONTENT] as const,
    ['calculator', CALCULATOR_CONTENT] as const,
  ])('assembles %s without throwing', (id, content) => {
    const out = assembleApp(baseInput(id, content));
    expect(out.html).toContain('<!DOCTYPE html>');
    expect(out.html).toContain('</html>');
    expect(out.manifest.archetype_id).toBe(id);
    expect(out.manifest.rendered_components.length).toBeGreaterThan(0);
    expect(out.manifest.html_bytes).toBe(out.html.length);
  });

  it('strategy: contains hero title, Homer wizard markup, paywall modal, result wrapper', () => {
    const out = assembleApp(baseInput('strategy', STRATEGY_CONTENT));
    expect(out.html).toContain(STRATEGY_CONTENT.hero.title);
    // Multi-step inputs now compose the Homer c_wizard catalog component
    // (not the old hand-rolled .tx-wizard-step markup).
    expect(out.html).toContain('data-wizard');          // Homer wizard wrapper
    expect(out.html).toContain('wizard-tabs');          // Homer nav tabs
    expect(out.html).toContain('data-wizard-content');  // Homer tab-pane container
    expect(out.html).toContain('btn-check');            // radio-cards (Homer button-radio)
    expect(out.html).not.toContain('tx-wizard-step');   // old hand-rolled markup gone
    // 'wizard' is recorded so form-wizard.js is auto-loaded.
    expect(out.manifest.rendered_components).toContain('wizard');
    expect(out.html).toContain('/homer/js/pages/form-wizard.js');
    expect(out.html).toContain('tx-phase-paywall');
    expect(out.html).toContain('txapp-result');
    // CTA url placeholder should be substituted.
    expect(out.html).toContain('https://example.com/op');
    expect(out.html).not.toContain('cta_url_placeholder');
  });

  it('assessment: emits scoring script with inlined data', () => {
    const out = assembleApp(baseInput('assessment', ASSESSMENT_CONTENT));
    expect(out.html).toContain('window.__txAssembler.scoring');
    expect(out.html).toContain('max_score');
    // Three candidate types were registered; the manifest should record
    // selections for each question with the appropriate component_id.
    expect(out.manifest.candidate_selections.length).toBeGreaterThanOrEqual(6);
    // Verify one star-rating selection happened (q4 in the fixture).
    expect(out.manifest.candidate_selections.some((s) =>
      s.selected_component_id === 'star-rating',
    )).toBe(true);
  });

  it('calculator: emits calculator runtime + chart is rendered for declared chart.type', () => {
    const out = assembleApp(baseInput('calculator', CALCULATOR_CONTENT));
    expect(out.html).toContain('window.__txAssembler.calculator');
    // chart.type === 'bar' → chart-bar rendered, chart-doughnut skipped.
    expect(out.manifest.rendered_components).toContain('chart-bar');
    expect(out.manifest.rendered_components).not.toContain('chart-doughnut');
  });

  it('emits Homer CSS + JS dependencies with absolute frontend URLs', () => {
    const out = assembleApp(baseInput('strategy', STRATEGY_CONTENT));
    expect(out.html).toContain('https://textos-web-test.example.pages.dev/homer/css/vendors.min.css');
    expect(out.html).toContain('https://textos-web-test.example.pages.dev/homer/css/app.min.css');
    expect(out.html).toContain('https://textos-web-test.example.pages.dev/homer/js/vendors.min.js');
    expect(out.html).toContain('https://textos-web-test.example.pages.dev/homer/js/app.mini.js');
  });

  it('emits PDF block', () => {
    const out = assembleApp(baseInput('strategy', STRATEGY_CONTENT));
    expect(out.html).toContain('txapp-pdf-btn');
    expect(out.html).toContain('Download as PDF');
    expect(out.html).toContain('Generated by Idea Corp');
  });

  it('emits event-tracking script wired to api_base', () => {
    const out = assembleApp(baseInput('strategy', STRATEGY_CONTENT));
    expect(out.html).toContain('https://textos-agent-test.example.workers.dev');
    expect(out.html).toContain('tx_vt_'); // visitor-token localStorage key
    expect(out.html).toContain('app_loaded');
  });
});
