// Shared PDF print block — extracted from the existing
// generate-business-app-html.ts pipeline so the new assembler-driven
// path and the legacy LLM-only path emit the same Download-as-PDF
// affordance + print stylesheet.
//
// The block consists of an inline <style> + <script> pair that:
//   - lives inside the iframe document
//   - finds the .txapp-result wrapper (or a permissive fallback like
//     #result, .result, [class*=outcome])
//   - injects a "Download as PDF" button into that wrapper
//   - sets up a print-only stylesheet that isolates the result content
//     and adds a branded footer
//
// Differences from the legacy pipeline:
//   - The legacy block is interpolated inside a TypeScript template
//     literal that already has `business.name` and `business.slug` in
//     scope; here we accept them as a parameter so the assembler can
//     call this from any context.
//   - Accent color comes in as a parameter rather than being read from
//     a `design` object. Falls back to amber #f59e0b like the legacy
//     code.
//   - The .txapp-result wrapper is added automatically by the assembler
//     around the result phase, so the LLM-compliance fallback selector
//     chain is shorter than the legacy version (which had to deal with
//     pre-contract apps).

export interface PdfBlockOptions {
  /** Hex string with leading #. Falls back to #f59e0b. */
  accent_hex?: string;
  /** Used in the "Generated by" footer. */
  business_name: string;
  /** Used in the footer URL line. */
  business_url: string;
}

export function buildPdfBlock(opts: PdfBlockOptions): string {
  const accent = opts.accent_hex && /^#[0-9a-fA-F]{3,8}$/.test(opts.accent_hex)
    ? opts.accent_hex
    : '#f59e0b';
  const name = String(opts.business_name).replace(/</g, '&lt;');
  const url = opts.business_url;
  // Escape single-quote in the footer text for the JS string literal.
  const footerNameJs = name.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  const footerUrlJs = url.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  return `
<style>
  .txapp-result { position: relative; padding-top: 52px; }
  .txapp-pdf-btn {
    position: absolute; top: 12px; right: 12px;
    background: ${accent}; color: #fff; border: none;
    padding: 7px 12px; border-radius: 6px;
    font-family: inherit; font-size: 12px; font-weight: 600;
    letter-spacing: 0.04em; cursor: pointer; z-index: 50;
    box-shadow: 0 2px 6px rgba(0,0,0,0.12);
  }
  .txapp-pdf-btn:hover { opacity: 0.9; }
  .txapp-pdf-footer { display: none; }
  @media print {
    body * { visibility: hidden !important; }
    .txapp-result, .txapp-result * { visibility: visible !important; }
    .txapp-result {
      position: absolute !important; top: 0; left: 0; right: 0;
      padding: 0 !important; background: #fff !important;
    }
    .txapp-result, .txapp-result * {
      color: #000 !important; background: transparent !important;
      box-shadow: none !important; text-shadow: none !important;
    }
    .txapp-result h1, .txapp-result h2, .txapp-result h3 { color: ${accent} !important; }
    .txapp-pdf-btn { display: none !important; }
    .txapp-pdf-footer {
      display: block !important; margin-top: 24px; padding-top: 12px;
      border-top: 1px solid #ccc; font-size: 11px; color: #555 !important;
    }
    @page { margin: 0.75in; }
  }
</style>
<script>
  (function () {
    function findResultWrapper() {
      var canonical = document.querySelector('.txapp-result');
      if (canonical) return canonical;
      var raw = Array.prototype.slice.call(document.querySelectorAll(
        '[id*="result" i], [class*="result" i], [id*="outcome" i], [class*="outcome" i]'
      ));
      if (raw.length === 0) return null;
      var wrappers = raw.filter(function (el) {
        var t = (el.tagName || '').toLowerCase();
        return t === 'div' || t === 'section' || t === 'article' || t === 'main';
      });
      if (wrappers.length === 0) wrappers = raw;
      var outer = wrappers.filter(function (el) {
        return !wrappers.some(function (o) { return o !== el && o.contains(el); });
      });
      if (outer.length === 0) outer = wrappers;
      outer.sort(function (a, b) {
        return (b.textContent || '').length - (a.textContent || '').length;
      });
      return outer[0] || null;
    }
    function attach() {
      var r = findResultWrapper();
      if (!r) {
        console.log('[txapp-pdf] no result wrapper found — PDF button skipped');
        return;
      }
      if (r.dataset.txPdfWired === '1') return;
      r.dataset.txPdfWired = '1';
      if (!r.classList.contains('txapp-result')) r.classList.add('txapp-result');
      var btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'txapp-pdf-btn';
      btn.textContent = 'Download as PDF';
      btn.addEventListener('click', function () { window.print(); });
      r.appendChild(btn);
      var foot = document.createElement('div');
      foot.className = 'txapp-pdf-footer';
      foot.textContent = 'Generated by ${footerNameJs} — ${footerUrlJs}';
      r.appendChild(foot);
    }
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', attach);
    } else {
      attach();
    }
  })();
</script>
`.trim();
}
