import type { TaskCtx, TaskResult } from "./types";
import { extractErrorMessage } from "../extract-error";

function stripFences(s: string): string {
  return s.replace(/^```json\s*/i, "").replace(/^```\s*/i, "").replace(/\s*```$/i, "").trim();
}

// Link token map — Claude writes these tokens in the body where each
// link should appear; we substitute them server-side. Keeps the LLM out
// of HTML/anchor-tag formatting (which it tends to over-style) and gives
// us full control over what shows up in both HTML and plain-text bodies.
type LinkSpec = { label: string; url: string };

function buildLinkMap(urls: {
  builder: string; manager: string; website: string; school: string;
}): Record<string, LinkSpec> {
  return {
    "[BUILDER]": { label: "🏗️  Your Builder",      url: urls.builder },
    "[MANAGER]": { label: "📊  Business Manager",   url: urls.manager },
    "[WEBSITE]": { label: "🌐  Your New Website",   url: urls.website },
    "[SCHOOL]":  { label: "🎓  Operator School",    url: urls.school  },
  };
}

// Replace [BUILDER] etc. with rich anchor tags. Inline styles only —
// external CSS gets stripped by Gmail/Outlook/etc.
function toHtmlBody(rawBody: string, linkMap: Record<string, LinkSpec>): string {
  let body = rawBody;
  for (const [token, { label, url }] of Object.entries(linkMap)) {
    const anchor =
      `<a href="${url}" style="color:#00a8cc;font-weight:700;text-decoration:none;font-size:17px">${label}</a>`;
    body = body.split(token).join(anchor);
  }
  // Escape any remaining stray HTML in the raw body (defensive — LLM
  // shouldn't be emitting raw <tags> but just in case).
  // We DO NOT escape the substituted anchors because they were inserted
  // after this point... so this is tricky. Skip escaping for V1 since
  // Claude is well-behaved here and the body is plain-text shape.
  // Convert paragraphs (blank-line separated) and line breaks to HTML.
  const paragraphs = body.split(/\n\s*\n+/).map((p) => p.trim()).filter(Boolean);
  const htmlParas = paragraphs
    .map((p) => `<p style="margin:0 0 1em 0">${p.replace(/\n/g, "<br>")}</p>`)
    .join("\n");

  return [
    `<!DOCTYPE html>`,
    `<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>`,
    `<body style="margin:0;padding:0;background:#f5f5f7">`,
    `<div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;font-size:15px;line-height:1.6;color:#1a1a1a;max-width:600px;margin:0 auto;padding:32px 24px;background:#ffffff">`,
    htmlParas,
    `</div></body></html>`,
  ].join("\n");
}

// Plain-text version of the body — kept as a fallback for email clients
// that don't render HTML (rare in 2026 but multipart is the email
// standard). Each token becomes "Label — https://url".
function toPlainBody(rawBody: string, linkMap: Record<string, LinkSpec>): string {
  let body = rawBody;
  for (const [token, { label, url }] of Object.entries(linkMap)) {
    body = body.split(token).join(`${label} — ${url}`);
  }
  return body;
}

export async function runWelcomeEmail(tc: TaskCtx): Promise<TaskResult> {
  const { business, ctx, user, anthropic, env, emit, supabase, taskRunId } = tc;

  await emit({ type: "cmd", text: "Drafting welcome email from agent context", ts: Date.now() });

  // Hardcoded to app.textos.ai — welcome email always points at the
  // production surface, even when generated by a test-mode worker.
  const APP = "https://app.textos.ai";
  const urls = {
    builder: `${APP}/business/${business.slug}/builder`,
    manager: `${APP}/business/${business.slug}/manage`,
    website: `${APP}/sites/${business.slug}`,
    school:  `${APP}/operator-school`,
  };
  const linkMap = buildLinkMap(urls);
  const agentName = ctx.agent_name ?? "your TextOS agent";

  const prompt = `Write a short, exciting welcome email for someone who just created their first business in TextOS.

CONTEXT
Business name: ${business.name}
Industry: ${ctx.industry ?? "their industry"}
Agent name (the AI assistant assigned to this user — sign the email as them): ${agentName}
What we know about the business: ${ctx.business_summary ?? "(nothing yet)"}
Value proposition: ${ctx.value_proposition ?? "(none yet)"}
Tone: ${ctx.brand_voice ?? "confident, direct, energetic"}

LINK TOKENS — write each token on a line by itself where you want the link to appear.
Each token becomes a clickable link when the email is sent. You do NOT write the URL
or any HTML — just place the token on its own line.

[BUILDER]   — replaces with a link to their Builder (command center for the agent)
[MANAGER]   — replaces with a link to the Business Manager (day-to-day operations view)
[WEBSITE]   — replaces with a link to their public website (THE EXCITING ONE — celebrate it)
[SCHOOL]    — replaces with a link to Operator School (short free lessons)

PRICING (mention briefly, near the end, NOT as the lead)
- $49.99/month subscription, includes 30 tokens
- Each paid task uses tokens; they can buy more tokens when they run out

SUPPORT
For any questions or issues, DM @TextOSApp on Twitter.

EMAIL STRUCTURE
- Subject line: punchy, max 60 chars, specific to ${business.name} or their industry.
- Body:
  • Opening greeting — generic ("Welcome to TextOS" or "Your business is live"). DO NOT invent a name for the user. We don't have their name. No "Hi [Name]" or "Hey [Name]".
  • One short paragraph celebrating that ${business.name} is real — reference the industry.
  • Then the four link tokens, each on its own line, followed by a one-sentence description in the agent's voice. Format:

      [BUILDER]
      Your command center. Direct the agent, see everything in one place.

      [MANAGER]
      Day-to-day operations…

      [WEBSITE]
      One short, excited sentence — this is the celebratory link.

      [SCHOOL]
      Short, free lessons on running your business.

  • One short paragraph on pricing + tokens.
  • One short line on support (DM @TextOSApp on Twitter).
  • Sign off as ${agentName}.

CONSTRAINTS
- Total length: easy to read in 30 seconds. Roughly 150-220 words.
- The body is converted to HTML for delivery, but you write it as plain prose with the link tokens. Don't write HTML.
- NO filler ("I hope this email finds you well", "in today's competitive landscape", etc.).
- The real goal is to get them excited about ${business.name} and make it obvious where to click next.
- Mention the overall vision once: TextOS makes it easy to run your entire business from one place.

Return ONLY valid JSON (no markdown, no backticks):
{
  "subject": "string",
  "body": "string — full email body with link tokens. Newlines as \\n.",
  "preview": "string — first 100 chars of body for dashboard display"
}`;

  const msg = await anthropic.messages.create({
    model: "claude-haiku-4-5-20251001",
    max_tokens: 800,
    messages: [{ role: "user", content: prompt }],
  });

  const raw = stripFences((msg.content[0] as { type: string; text: string }).text.trim());
  let parsed: { subject: string; body: string; preview: string };
  try {
    parsed = JSON.parse(raw);
  } catch {
    // Deterministic fallback — uses the same link tokens so the
    // substitution pipeline below works identically. Welcome email is
    // never empty/generic regardless of LLM behavior.
    const fallbackBody =
      `Welcome to TextOS.\n\n` +
      `${business.name} is live. We just finished researching the ${ctx.industry ?? "market"} ` +
      `and your task queue is ready to go.\n\n` +
      `Here's where to start:\n\n` +
      `[BUILDER]\n` +
      `Your command center. Direct the agent, watch ${business.name} come together. ` +
      `Tasks, documents, market sizing — all in one place.\n\n` +
      `[MANAGER]\n` +
      `Day-to-day operations. Check in on what's running and make decisions.\n\n` +
      `[WEBSITE]\n` +
      `Yes, ${business.name} has a real, live website. Go look at it.\n\n` +
      `[SCHOOL]\n` +
      `Short, free lessons on how to actually run the business.\n\n` +
      `When you're ready to unlock the full agent, it's $49.99/month and includes ` +
      `30 tokens for paid tasks. Top up anytime when you run low.\n\n` +
      `Our goal is simple: make it easy to run your entire business from one place. ` +
      `Any questions, DM us on Twitter at @TextOSApp.\n\n` +
      `— ${agentName}`;
    parsed = {
      subject: `${business.name} is live — what to do next`,
      body: fallbackBody,
      preview: `${business.name} is live. Your Builder, Business Manager, website, and Operator School are ready.`,
    };
  }

  // Substitute link tokens for both HTML and plain-text bodies. Sent as
  // multipart so HTML-capable clients render the rich version and the
  // rare plain-text client gets a readable fallback.
  const htmlBody  = toHtmlBody(parsed.body, linkMap);
  const plainBody = toPlainBody(parsed.body, linkMap);

  let sent = false;
  let sendError: string | undefined;

  if (env.SENDGRID_API_KEY && env.SENDGRID_API_KEY !== "PLACEHOLDER") {
    await emit({ type: "cmd", text: "Sending via SendGrid", ts: Date.now() });
    try {
      const res = await fetch("https://api.sendgrid.com/v3/mail/send", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${env.SENDGRID_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          personalizations: [{ to: [{ email: user.email }] }],
          from: { email: "hello@textos.ai", name: "TextOS" },
          subject: parsed.subject,
          // SendGrid spec: text/plain MUST come before text/html when both
          // are present (RFC 1341 — earlier parts are fallbacks).
          content: [
            { type: "text/plain", value: plainBody },
            { type: "text/html",  value: htmlBody  },
          ],
        }),
      });
      sent = res.ok;
      if (!res.ok) sendError = `SendGrid ${res.status}`;
    } catch (err) {
      sendError = extractErrorMessage(err);
    }
  } else {
    await emit({ type: "cmd", text: "SendGrid not configured — email staged for later", ts: Date.now() });
  }

  // ── Write to business_assets ────────────────────────────────────────
  // Store the token-form body (asset_text) so the dashboard preview can
  // render with the same substitution pipeline if we ever surface it.
  try {
    await supabase.from("business_assets").insert({
      business_id: business.id,
      task_run_id: taskRunId,
      asset_type: "email",
      asset_subtype: "welcome_email",
      asset_text: parsed.body,
      metadata: {
        model: "claude-haiku-4-5-20251001",
        subject: parsed.subject,
        to: user.email,
        sent,
        send_error: sendError ?? null,
        html_body: htmlBody,
        plain_body: plainBody,
      },
    });
  } catch {
    // Non-fatal
  }

  return {
    output_data: {
      subject: parsed.subject,
      body: parsed.body,
      preview: parsed.preview,
      sent,
      send_error: sendError ?? null,
    },
  };
}
